language: python
python:
  - "2.7"
sudo: true
before_install:
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
  - sudo apt-get update
  - sudo apt-get install --fix-missing
  - sudo apt-get install --no-install-recommends -qq poppler-utils ghostscript imagemagick --fix-missing
  - sudo apt-get install --no-install-recommends -qq libfile-fcntllock-perl gcc equivs libwww-perl fontconfig unzip
  - pdfinfo -v
  - compare -version
  - gs -v
  - sudo ./install-tl-ubuntu --only-apt-and-dpkg
  - sudo wget http://mirror.utexas.edu/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz -O install-tl-unx.tar.gz
  - tar -xf "install-tl-unx.tar.gz"
  - tl_dir=$( ls | grep -P "install-tl-\d{8}$" | head -n 1 )
  - cd "${tl_dir}"
install:
  - echo "i" | sudo -s ./install-tl -logfile install-tl.log -repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet -profile ../texlive.profile
  - MAINTEXDIR=$(grep "TEXDIR:" "install-tl.log" | awk -F'"' '{ print $2 }')
  - sudo ln -s "${MAINTEXDIR}/bin"/* "/opt/texbin"
  - sudo sed -i 's/^PATH="/PATH="\/opt\/texbin:/' /etc/environment
  - cd ..
  - source /etc/environment
  - source /etc/profile
  - source ~/.profile
  - unset _OLD_VIRTUAL_PATH
  - source ~/virtualenv/python2.7/bin/activate
  - sudo -i texhash
  - sudo -i tlmgr update --self --all
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - openssl aes-256-cbc -K $encrypted_06732d003ed9_key -iv $encrypted_06732d003ed9_iv -in travis-deploy-key.enc -out travis-deploy-key -d
  - chmod 600 travis-deploy-key
  - eval `ssh-agent -s`
  - ssh-add travis-deploy-key
  - cd test && scripts/travis-after.sh
