language: python

git:
  depth: 1

matrix:
  include:
    - name: "Linux - Latest TeX Live"
      env: TEST_SUITE=linux-latest
      os: linux
      sudo: required
      python: 2.7
    - name: "OS X - Latest TeX Live"
      env: TEST_SUITE=osx-latest
      os: osx
      sudo: required
      language: generic
      osx_image: xcode10
      before_install:
        - sw_vers
        - brew update
        - python2.7 --version
        - brew install libidn
        - brew install ghostscript
        - gs -v
        - brew install imagemagick
        - compare -version
        - brew install xpdf
        - pdfinfo -v || (exit 0)

install:
  - ci/travis_install_${TEST_SUITE}.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=/Library/TeX/Distributions/Programs/texbin:$PATH;
    fi
  - tlmgr conf
  - make install CONTINUE=y
  - sudo -i texhash
script:
  - make -C test
after_script:
  - ci/travis_after.sh
